[package]
name = "cargo-bundle"
version = "0.0.0"
authors = ["George Burton <burtonageo@gmail.com>"]
license = "MIT"
keywords = ["bundle", "cargo"]
repository = "https://github.com/burtonageo/cargo-bundle"
description = "Wrap rust executables in OS-specific app bundles"

[dependencies]
clap = "^2"
icns = "^0.2"
image = "^0.10"
plist = "0.*"
toml = "^0.1"
walkdir = "^0.1"
