enum_trailing_comma = false
fn_brace_style = "PreferSameLine"
format_strings = false
ideal_width = 90
max_width = 120
normalise_comments = false
reorder_imports = true
single_line_if_else = true
struct_trailing_comma = "Never"
struct_lit_trailing_comma = "Never"
struct_lit_width = 30